### ISSUE TITLE
install web3 issue - anyone can help?

### ISSUE THREAD

**Issue by charlesgao12** [yifon/SST_BlockChain#2]
Logs as below:

$ npm install web3 -g
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> scrypt@6.0.3 preinstall /nodejs/node-v8.9.1-linux-x64/lib/node_modules/web3/node_modules/scrypt
> node node-scrypt-preinstall.js

> scrypt@6.0.3 install /nodejs/node-v8.9.1-linux-x64/lib/node_modules/web3/node_modules/scrypt
> node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: Python executable "/usr/bin/python2" is v3.5.3, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at PythonFinder.failPythonVersion (/nodejs/node-v8.9.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (/nodejs/node-v8.9.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:474:14)
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:267:7)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
gyp ERR! System Linux 2.6.32-696.16.1.el6.x86_64
gyp ERR! command "/nodejs/node-v8.9.1-linux-x64/bin/node" "/nodejs/node-v8.9.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /nodejs/node-v8.9.1-linux-x64/lib/node_modules/web3/node_modules/scrypt
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/charles/.npm/_logs/2017-11-22T07_22_11_675Z-debug.log

**Comment by charlesgao12** [comment]
Should be nodejs /npm version issue. I reinstalled nodejs 8.9.1 on ubuntu and the result is positive.

**Comment by sivvi** [comment]
Check the error log as below.   
_gyp ERR! configure error
gyp ERR! stack Error: Python executable "/usr/bin/python2" is v3.5.3, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0._


It is caused by invalid Python version installed in the server.  I have fallback python version to 2.6.6 for root and retry.  Hit another issue as attached. 

_npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> scrypt@6.0.3 preinstall /nodejs/node-v8.9.1-linux-x64/lib/node_modules/web3/node_modules/scrypt
> node node-scrypt-preinstall.js

sh: node: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! scrypt@6.0.3 preinstall: `node node-scrypt-preinstall.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-11-25T11_47_29_602Z-debug.log_

**Comment by sivvi** [comment]
Supplement to my issue above.  
scrypt and web3 would get fail if we install software in global mode.  And, we should have to upgrade gcc version to 4.8 or above.  For this case, I upgrade gcc version to 4.8.2.  After then, use npm to install web3 and will get success.
